### PR TITLE
Add Changelog

### PR DESCRIPTION
**Pull request by kabilar**
Going forward we will update the version and changelog to track major updates to this repository. This commit establishes this process.

### CODE REVIEW

**Comment by kabilar** [comment]
Pending discussion of https://github.com/datajoint/datajoint-elements/issues/43.

**Comment by kabilar** [comment]
Hi @CBroz1, this pull request is ready for review.  Thanks!

**Review by CBroz1 — APPROVED** [review]

**Comment by CBroz1** [comment]
I see that this repo [doesn't yet have release tags](https://github.com/datajoint/workflow-array-ephys/releases/new) - what are the procedures for adding one? Is it sufficient for pinned requirements to simply specify in `version.py`, or do we also need to keep track with github releases?

**Comment by kabilar** [comment]
Thanks @CBroz1.  There are currently no procedures for adding tags to the `workflows`.  We will not be creating releases of the `workflows`.  The `elements` have the process for creating tags and releases built into GitHub Actions.  As the `workflows` are not a dependent of any packages, tagging/releasing is not as critical and primarily for documentation purposes.  I will create a GitHub Issue to automate a process for creating tags.

**Pull request merged**
