### PR TITLE
Update Docker and Compose files.  Add pytest fixture.

### PR DESCRIPTION
**Pull request by kabilar**
- Move Docker and Compose files to `docker` subdirectory
    - `git mv` wasn't working for `docker-compose-dev.yaml` so original file is deleted and a new file is created.
- Add pytest fixture `ephys_insertionlocation` for NWB export tests

### CODE REVIEW

**Comment by CBroz1** [comment]
Should this PR incorporate everything from PR #18? Will we try to merge this before or after ongoing work linking element-trial?

**Comment by kabilar** [comment]
> Should this PR incorporate everything from PR #18?
I will go through #18 and incorporate appropriate changes as our approach to the NWB export has changed since #18 was first proposed.

**Comment by kabilar** [comment]
> Will we try to merge this before or after ongoing work linking element-trial?

Let's merge the changes in this pull request before the work linking element-trial.  However, I will not include the NWB export pytests in this pull request.

**Comment by kabilar** [comment]
Hi @CBroz1, this pull request is ready for review.  Thanks.

**Pull request merged**
