### PR TITLE
Add GitHub Codespace environment and demo notebooks

### PR DESCRIPTION
**Pull request by kabilar**
- [x] Add Codespace devcontainers from `workflow-calcium-imaging` `main` branch
- [x] Add DataJoint config environment variables
- [x] Update requirements
- [x] Remove notebooks in anticipation of tutorial revamp
- [x] Remove jupytext synced scripts since GitHub now natively supports rich diffs with Jupyter notebooks.
- [x] Add demo notebooks
- [x] Update readme to mirror other repos.  Include instructions for interactive tutorials with GitHub Codespaces.

### CODE REVIEW

**Review by kushalbakshi — COMMENTED** [review]
Hi @kabilar, the codespace is working without any major issues. Just a couple of small suggestions. We should add `example_data/` to `.gitignore` and remove the following line from `demo_prepare.ipynb`: 
```
ephys.Curation().create1_from_clustering_task(clustering_key)
```
It throws an error since we're using `ephys_no_curation`. We're ready to merge after that.

**Comment by kabilar** [comment]
> Hi @kabilar, the codespace is working without any major issues. Just a couple of small suggestions. We should add `example_data/` to `.gitignore` and remove the following line from `demo_prepare.ipynb`:
> 
> ```
> ephys.Curation().create1_from_clustering_task(clustering_key)
> ```
> 
> It throws an error since we're using `ephys_no_curation`. We're ready to merge after that.

Thanks @kushalbakshi.  On GitHub Codespace, I was defaulting to using the `ephys_acute` module ([see default setting](https://github.com/kabilar/workflow-array-ephys/blob/5ffc035a201ab874b515c4a55a75d33fc9bf8c38/workflow_array_ephys/pipeline.py#L27)).  Could it be that you are setting the ephys mode to `ephys-no-curation` in your local `dj_local_conf`?

**Comment by kabilar** [comment]
Added an `EPHYS_MODE` environment variable to the Dockerfile to explicitly use the `ephys_acute` module.

**Comment by kushalbakshi** [comment]
> > Hi @kabilar, the codespace is working without any major issues. Just a couple of small suggestions. We should add `example_data/` to `.gitignore` and remove the following line from `demo_prepare.ipynb`:
> > ```
> > ephys.Curation().create1_from_clustering_task(clustering_key)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It throws an error since we're using `ephys_no_curation`. We're ready to merge after that.
> 
> Thanks @kushalbakshi. On GitHub Codespace, I was defaulting to using the `ephys_acute` module ([see default setting](https://github.com/kabilar/workflow-array-ephys/blob/5ffc035a201ab874b515c4a55a75d33fc9bf8c38/workflow_array_ephys/pipeline.py#L27)). Could it be that you are setting the ephys mode to `ephys-no-curation` in your `dj_local_conf`?

I think there's definitely an issue on my end. Since it's working in your testing, I'm proceeding with the merge. Thank you!

**Review by kushalbakshi — APPROVED** [review]

**Comment by kabilar** [comment]
[Version 0.3.0](https://github.com/datajoint/workflow-array-ephys/releases/tag/0.3.0) is tagged and released.

**Pull request merged**
